networks:
  rent-o-meter:

volumes:
  db:

services:
  backend:
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8892:8892"
    build:
      context: ./backend
    networks:
      - rent-o-meter
    volumes:
#   относительный путь относительно файла docker-compose.yml : абсолютный путь внутри контейнера
      - ./backend/.env:/usr/src/app/.env

  frontend:
    restart: unless-stopped
    ports:
      - "8893:8893"
    build:
      context: ./frontend
    volumes:
      #   относительный путь относительно файла docker-compose.yml : абсолютный путь внутри контейнера
      - ./frontend/src/app/env/:/usr/src/app/.env/

    networks:
      - rent-o-meter

  db:
    networks:
      - rent-o-meter
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
